### ISSUE TITLE
Socket Bind Error

### ISSUE THREAD

**Issue by a7cross7** [jacktrip/jacktrip#475]
I have mostly had success with running Jacktrip from my Windows 10 PC as a hub server and others connecting to it for over a year. 

I've been trying to connect to the hub server from a Linux Mint computer on my own home network and, while I am able to connect as a peer-to-peer connection, it does not want to connect to the hub server. When I try to connect to the hub server with the Linux machine it give a Socket Bind Error and does not connect for any length of time. Do I need to reference the server differently when it's on LAN versus connecting to it from the broader Internet? 

I tried this with my son a few months ago from his Windows 10 PC and he had the same issue trying to connect on our home network. I think it also gave a Socket Bind Error.

I've seen some threads from years back that seem to have been similar, but I've not seen any of the resolutions to those threads.

I'm running v1.3.0 on the Windows 10 machine and v 1.0.5 on the Mint machine.

I'm also wondering if there is a version of Jacktrip and Jack that will run on Windows 11?

Any assistance would be appreciated. Thanks.

Andy Cross

**Comment by SynthiaPayne** [comment]
Hi!

I'm running JACK 1.9.20, and JackTrip 1.5.1 on Windows 11. Although my 
machine OS is 64-bit, I had to install both the 64-bit and 32-bit 
versions of JACK 1.9.20 in order for it to run. I did not have this 
problem with JACK 1.9.19 on the same Win11 machine, but did have it with 
a Win10 machine a few versions ago. I'm not sure what the problem is or 
why it works when I have both versions installed.

Regarding the socket error, you might already know that each instance of 
JackTrip on the same network, whether server or client, needs its own 
port number. Also, that the hub server runs on port 61002-62000 UDP and 
4464-4494 TCP, and the client on 4464-4494.

If you have both a server and client on the same machine, Mike O'Connor 
has a thread on the JackTrip googlegroup - 
https://groups.google.com/g/jacktrip-users - Look for "new jacktrip 
1.4.0" on 11/7/2021 at 12:12PM

Hope this helps some. Please let me know if you have more questions for me.

synthia

**Comment by a7cross7** [comment]
Thanks! This is very helpful and gives me a few new things to try.

Andy

**Comment by a7cross7** [comment]
I can't say that this got me anything much new on my end. I guess I'm not
exactly clear what you mean when you write:




*Regarding the socket error, you might already know that each instance
ofJackTrip on the same network, whether server or client, needs its ownport
number. Also, that the hub server runs on port 61002-62000 UDP and4464-4494
TCP, and the client on 4464-4494.*

I've always run my hub server from my Windows 10 machine and set it up with
port 4464 set for UDP/TCP and ports 61002 - 61009 to UDP all for the
Windows 10 machine. When others connect they each grab one of the 61000
ports for their connection in increasing order of connection. I've never
had to set the 4464 port to another port. I tried that and was only able to
offset the port numbers on the server end. I tried an offset of 1 but it
still didn't connect. I left the client on the 4464 port. The message on my
Linux client machine is as follows following the "jacktrip -C IPaddress"
command:

SETTING ALL PORTS
Setting JACK Process Callback...
SUCCESS
---------------------------------------------------------
The Sampling Rate is: 48000
The Audio Buffer Size is: 256 samples
                                    or: 1024 bytes
----------------------------------------------------------
The Number of Channels is: 2
---------------------------------------------------------
Using UDP Protocol
----------------------------------------------------------
Waiting for server response...
terminate called after throwing an isntance of 'std::runtime_error'
  what():   ERROR:  UDP Socket Bind Error
Aborted

I'm not sure what I have wrong. It seems to almost be connecting but
something, obviously, is not right...

Andy

**Comment by SynthiaPayne** [comment]
hmm...have you ever done port forwarding for connecting as a hub server? 
That is, logging into your router and manually opening ports?

**Comment by a7cross7** [comment]
Yes. Actually for the firewall associated with the router as well as that
for my virus protection software. That hasn't seemed to resolve the problem
when both computers are on the same LAN, or at least I haven't figured out
how yet.

**Comment by SynthiaPayne** [comment]
is it possible that your local IP address changed? Mine did, and I had 
to adjust my port forward settings.

sorry it was not clear what I said about the client TCP port: as you 
said, the first client connection will be on 4464. Subsequent client 
connections would need a port offset for each one. The server designates 
it in the command line, and the client uses the same port offset.

**Comment by a7cross7** [comment]
My public IP address has changed now and then but when I connect
successfully within my private LAN using a peer to peer connection I always
used the internal IP address within the LAN. I've never successfully
connected to my own server from within my network using the public IP
address.

**Comment by SynthiaPayne** [comment]
sorry I should be more specific, local and internal are the same - it 
was the internal IP addresses of the machines on my LAN changed! It was 
totally unexpected.

so, the Linux client is using the internal IP address of the server 
*machine* on your LAN in the command line, right?

Have you used any of the network scanning tools like netscan or iPerf?

**Comment by a7cross7** [comment]
I've never been able to connect to a hub server from a client within my
private LAN either.

**Comment by a7cross7** [comment]
Yes. I've used the local IP address of the hub server in the command line.
No, I haven't tried netscan or iPerf?

**Comment by SynthiaPayne** [comment]
here are a couple of resources - I am not using Linux.

are you using JACK and JackTrip together?
https://jackaudio.org/faq/linux_rt_config.html

there's a thread on the jacktrip googlegroup that might be useful to 
you, although they are using ubuntu it might help.
look for the thread entitled, "jack/jacktrip ubuntu 18.04 server" on 
9/13/2020 started by Daniele Buatti.

https://groups.google.com/g/jacktrip-users

synthia

**Comment by a7cross7** [comment]
Thanks! I'll do some more digging tomorrow.

**Comment by ntonnaett** [comment]
Could you try a more recent version of JackTrip? We fixed a lot of bugs since version 1.0.5.

**Comment by ntonnaett** [comment]
Looks like this was fixed with version 1.1 in 2015:
https://bugs.launchpad.net/ubuntu/+source/jacktrip/+bug/1411455
https://github.com/jacktrip/jacktrip/issues/13

You should update your distribution.

**Comment by a7cross7** [comment]
When I try to install version Jacktrip 1.1 it seems to say an AMD 64 is
required, I think, and this system is incopatible. My system is a lowly
Intel Atom N550. It's a small netbook. Hopefully I should be able to run
some version on this machine?

**Comment by ntonnaett** [comment]
The Intel Atom N550 is capable of AMD64 (or Intel 64 to be precise). But you probably installed a 32bit version of Linux Mint. So not only to run a newer version of JackTrip but also for your own security, you should install a recent Linux Mint version (64bit).

**Comment by a7cross7** [comment]
Thanks. I'll give that a try.

**Comment by a7cross7** [comment]
Well, thanks for those suggestions. They cleared up most of my issues.

I installed the Linux Mint version 20.3, which allowed me to install the
Jacktrip version 1.1. I also am using Qjackctl version 0.5.0, which perhaps
I should update, I'm not sure.

I still have a few outstanding issues and I need to try this out from
outside of my local area network next. My outstanding issues are:

   1. Audio controls on the Mint netbook are strange. When I use the USB
   Blue Yeti mic for Jacktrip, I do not seem to be able to turn off the
   netbook audio and still have the audio from the mic. I do not have any
   audio coming through the mic to my headphones, whether or not I turn
   the speakers on the netbook on. I only seem to be able to plug the
   headphones into the netbook, which seems to combine audio from the netbook
   mic and the Yeti mic. Likewise, I do not seem to be able to turn off the
   netbook mic and still get audio from the Yeti mic. Perhaps these issues are
   indicators I should upgrade the Qjackctl software, I'm not sure.
   2. I have now successfully connected the Mint netbook to a hub server
   running Jacktrip on a Windows 10 machine, both on my local area network. I
   have not, however, been successful in starting a server on the Mint netbook
   and connecting my Windows 10 computer to it as a client. It seems to hang
   both the client and the server "Waiting for (peer or client)". I also note
   that they both seem to almost connect with the client reporting "Server
   Address set to: 192.168.0.25 Port: 61000", which I think is different from
   the Windows 10 server, which, I think, sets the port to 61002. The Mint
   netbook server reports: "Client UDP Port is = 4464" then "Client TCP
   Socket Closed!". Lastly, "Waiting for client connection...". No connection
   seems to take place.

Thanks for all of your help. This has gotten me a long way toward
functionality.

Andy Cross

**Comment by ntonnaett** [comment]
I close this because the original issue is solved.

But some hints: JACK only runs with one device. There are some tricks that are all not quite good. The only real solution is to use pipewire. But Linux Mint is surprisingly old and probably won't have it in the next 5 years.

If the second problem also occurs with the latest JackTrip version, please open a new issue. You might just want to run the build from our release page: https://github.com/jacktrip/jacktrip/releases/tag/v1.5.1

**Comment by psiborg112** [comment]
To add to what @ntonnaett has said, the networking code has undergone several major revisions since version 1.1 and a lot of bugs have been fixed in the process. (The same can be said of the hub server code.) Running the most recent version is really the way to go here.
