### ISSUE TITLE
Can't connect to jacktrip server (in hub mode) in a container with remapped ports

### ISSUE THREAD

**Issue by 2xbass** [jacktrip/jacktrip#519]
I am trying to run jacktrip in hub server mode in a container and having issues. At least the server seems fine but I can't seem to connect to the mapped ports.

Am I correct that I should be using -U to specify a different base port (which would normally be 61002) and -B for the connection (which would usually be 4464)?

**Comment by ntonnaett** [comment]
Those might be of interest:
https://github.com/ntonnaett/docker-jacktrip
https://github.com/ntonnaett/dockemu-ansible/tree/main/roles/preparation/files/jacktrip/server

The first one misses the EXPOSE for the UDP ports: `EXPOSE 61002-61100/udp`

**Comment by 2xbass** [comment]
@ntonnaett thanks for chiming in. Currently I have this:

EXPOSE 4464/tcp
EXPOSE 4464/udp
EXPOSE 61002-61010/udp

I just chose 61010 as an arbitrary number now for testing and am only even initially trying to get one or two clients going. I'm not able to make connections at all and not sure what's happening. I take it you are able to connect successfully to your containers? What parameters are you using on the client end to make the connections?

**Comment by ntonnaett** [comment]
I'm working with the ansible setup right now. I don't remember how I used just the docker container. But I remember that it worked.

**Comment by ntonnaett** [comment]
With this setup you are using the network from the host. So connecting to the container means `jacktrip -C localhost` from your host.

**Comment by 2xbass** [comment]
In my setup I'm only running the server (in hub mode) in the container and the clients are running elsewhere. I know everything works fine as I'm also running Jamulus servers in the same container and there are no issues connecting to those (from clients outside the container). What's not clear to me is even precisely which command-line args to use with -C in order to make the connections. I think it's -U with the remapped UDP port (that would usually be 61002) and -B with the remapped port (which would usually be 4464) but I'm not 100% sure. At least when I do -C -U 61002 to -B 4464 on a VM (no container) it works.

**Comment by ntonnaett** [comment]
As you said, `-U` is for the udp base port. That's for the server side. Did you try to just connect? With `-B` you can use a different udp port (on the client side). Why do you want to set it at all?

**Comment by 2xbass** [comment]
Connecting without any additional args on the client side doesn't work and I wouldn't expect it too since the ports are being remapped. The client has to know what those different ports are.

Thanks for clarifying that -U is only a server-side arg. The thing is, the server running in the container shouldn't need to use that arg since in the container it thinks it is running on 61002. It is only the client that needs to specify a different port.

**Comment by ntonnaett** [comment]
Could you post complete commands you are using? If you don't change any port on the server, the client shouldn't need to specify any port.

**Comment by ntonnaett** [comment]
And what ports are you remapping?

**Comment by 2xbass** [comment]
@ntonnaett I'm trying to map 4464 (UDP and TCP although I believe for running in hub mode I should only need to remap 4464) and a range of ports starting from 61002 (for UDP).

There are no different commands used because as far as the server is concerned, it is running on the original ports. Hence. I just run the server with "jacktrip -S -q24 -p2". I know this works because I run many other servers in containers and even in this case I have a Jamulus server running the same container and it all works fine as long as the client knows which port to connect to. In the case of jacktrip, I believe it needs to be possible to tell the client a) which port to connect to instead of 4464 and b) which port to listen on instead of 61002. However since I believe each client uses a different port starting at a certain base, then the client needs to know the new base. Looking at the command-line args, -U is the only option that allows a difference base to be specified.

**Comment by ntonnaett** [comment]
If you remap 4464/tcp then the client needs to set the server port with `-P remapped_serverport`. The rest is handled by jacktrip.

**Comment by 2xbass** [comment]
@ntonnaett that only half works. The client does report "Waiting for Peer..." which I believe indicates it made the connection, but it sits indefinitely on that instead of reporting "Received Connection from Peer!" I believe it's waiting for a response on 61002 which will never come because the server is sending back on a remapped port and I can't seem to figure out how to tell the client which port that is.

**Comment by ntonnaett** [comment]
Yeah… Usually the application would just use the port from where the udp packet came from. But jacktrip's protocol is more complicated there. The problem is that server and client negotiate those ports. And they use those unremapped ports. I think there's a developer meeting on thursday where we can talk about this.

**Comment by 2xbass** [comment]
@ntonnaett thank you for all your discussion on this. If you have a way to poke on this further I'd appreciate it.

**Comment by ntonnaett** [comment]
You would need to look into UdpHubListener.cpp and try to understand how the connection is made.

**Comment by psiborg112** [comment]
I will preface this by saying that I have no experience whatsoever with docker, but If you haven't already, get rid of EXPOSE 4464/udp. That's the port that the client will be expecting a response on (unless you've explicitly specified another port using -B on the client side), and possibly why it's stuck waiting for one. UDP traffic to the server only happens on ports above the base port that you specify. (Or 61002 by default.)

Ignoring for a second the extensions that I've made to the initial handshake for authentication and setting a remote client name, basically the client sends the number of its UDP listening port (by default 4464) to the server over TCP and then the server sends back the first available port above the UDP base port and starts to listen on that port with a temporary socket. The client starts sending jacktrip traffic to this port, and the server inspects the first packet it receives to determine the actual UDP port of the client in case there's a mismatch. (Jacktrip sends and receives UDP packets from the same port using a single socket.) It then starts up a jacktrip thread which will start sending traffic to the client on the UDP port gleaned from the packet header. (That covers the process outlined in UdpHubListener.cpp, JackTrip.cpp and JackTripWorker.cpp.)

**Comment by ntonnaett** [comment]
The problem I see is that the server sends the udp port in the jacktrip header. The router or anything else that remaps this port stops this from working. The client should just respond to the port the udp packets came from. I think we do this already at some points but not everywhere.

What might work better:
1. server listens on 4464/tcp
2. client opens a port on udp
3. client connects from the same port to server 4464/tcp (this should do the trick for the port mapping in the client's router)
4. server sends udp to client
5. client answers to the udp port where the udp packet came from (this should fix the mapping for the server side)

What of these breaks compatibility with old versions?

**Comment by 2xbass** [comment]
@psiborg112 thanks for clarifying there's no need for UDP 4464. I thought that was the case since my understanding is that in hub server mode 4464 is only TCP. I will remove that however I expect that this will still not work without changes (perhaps like those suggested by @ntonnaett) because if the server sends back say 61002 as the port for the client to listen on, it's not going to be that port but will instead be some remapped port. When you run something in a container, docker tells you what the ports were remapped to so it is possible to get this info but it would require modifying jacktrip on the client end. I think in this case, the client-server protocol is not container-friendly which is a pity. So many other services, including Jamulus, easily run in a container and you just need to know from the client side, what port to connect to instead of the default port. It makes it a lot more possible to run the service in many places and to make better use of server resources.

**Comment by 2xbass** [comment]
I should also add that in containers, the a sequence of ports is not guaranteed to map sequentially another sequence of ports. 61002 and 61003 could be mapped to wildly different ports.

**Comment by psiborg112** [comment]
There's no way that I can see to make that sequence of events backwards compatible with what happens now. You'll have a stand off between newer clients and older servers where they're both waiting for the other end to send the first UDP packet. Also, I'm not sure exactly how step 3 is working there.

**Comment by psiborg112** [comment]
(Connect is the wrong word because it's UDP, but what I meant was it's the port that the client will send data to, not the port that the client will listen on.)

**Comment by ntonnaett** [comment]
No. I described what I think might work, not what the current protocol is. If the server sends the port to connect to, remapping can't work. Putting the port in our header is just a bad idea in my opinion. The port is already in every udp and tcp header and gets changed when remapped.
The problem is the switch from tcp to udp in jacktrip. But if we used the same port for udp and tcp on the client side (step 3), we know what port is used and the port has probably got a mapping between router and client. But that probably won't work for every router.

**Comment by ntonnaett** [comment]
Oh, sorry. That was a clarification of your description of the current implementation.

**Comment by psiborg112** [comment]
Yeah, I don't think we can reliably assume that a router will map a tcp port and a udp port in the same way.

**Comment by psiborg112** [comment]
It's still going to break backwards compatibility, and could cause issues with multiple clients connecting from the same host or behind the same router.

**Comment by psiborg112** [comment]
(We can probably work around that second issue, but not the first.)

**Comment by ntonnaett** [comment]
That's work for a successor protocol.
