### ISSUE TITLE
Issue with login to virtual studio account

### ISSUE THREAD

**Issue by forsythac** [jacktrip/jacktrip#615]
We are seeing an issue where the app hangs on "Logging in..." on some Linux platforms.

**We also have one reported issue with this behavior on Mac**. User is reporting that no browser tab is opened when the app tries to log in, and the app hangs on "Logging in..."

screen shot from user
![login issue](https://user-images.githubusercontent.com/3578658/172493223-dfa1eb29-2fee-4ef5-846b-bcf809fb1361.jpg)

quick reproduction of issue on VM:
https://user-images.githubusercontent.com/3578658/172493780-dc0596d5-a086-4e6c-a83e-c67ae335665e.mp4

Note that in the video above Russ had to launch firefox to get it to show "Virtual Studio Login Successful!" and that the app did not get the memo about that.

**Comment by Rjapeck** [comment]
To add on to this, I took a much longer video. If I delete the config file created when you first launch the app you are returned to the first status the app is in. However, it just goes back to the same screen that it got hung on the first time

https://user-images.githubusercontent.com/105318997/172500044-2ddb22c6-6f0c-48ce-9358-ad1de00b1b61.mp4

.

**Comment by mattahorton** [comment]
I repro'd myself on Ubuntu. Not on Mac though.

**Comment by psiborg112** [comment]
Can't reproduce here on any platform, so I'm not going to be much help debugging this. Is there any terminal output associated with is? Is the lambda function even being called? (Can someone try adding some debugging cout lines to it?)

**Comment by psiborg112** [comment]
Which linux version is being used for this? (Built locally? Binary? Flatpack? Is there someone facing these issues who is capable of creating a local build?)

**Comment by forsythac** [comment]
I'll chime in that I was able to get the Mac user sorted by cleaning out the temp files with https://freemacsoft.net/appcleaner/ and installing the latest version (they had been on rc1 before). So, there are currently no known outstanding issues on Mac.

**Comment by psiborg112** [comment]
My suspicion is that there's potentially some system setup that is causing QDesktopServices::openUrl to fail. So when the authorizeWithBrowser signal fires on our m_authenticator object, Qt isn't finding a way to open the URL. When called directly, QDesktopServices::openUrl has a boolean return state. It would be worth manually trying to open a URL (can be any arbitrary URL) at the start of the login function and checking the return value of this function to see if this is the actual issue or whether we need to look elsewhere.

**Comment by psiborg112** [comment]
In the browser launch check branch that I've just uploaded you'll be able to see whether or not there's an attempt to launch the browser and whether that's been successful or not.

**Comment by Rjapeck** [comment]
https://user-images.githubusercontent.com/105318997/172957440-10ccb3e6-be77-4306-8c3c-48eb1a37415e.mp4
This is your branch and its output. @psiborg112

**Comment by Rjapeck** [comment]
To revert the app into the first launch state  @forsythac  
```
rm ~/.config/jacktrip/JackTrip.conf
```

**Comment by Rjapeck** [comment]
```qt.networkauth.replyhandler: Host requires authentication```

That's the new line of output returned by this build. (Seen at the end of the video)

**Comment by psiborg112** [comment]
Was this with the browser already open, or did the app manage to open it?

**Comment by psiborg112** [comment]
(Because this is different behaviour than was initially reported. While the outcome might be the same, the mechanism won't be. The debug statements I added were to work out where the browser was failing to launch.)

If it's getting "Host requires authentication" then that suggests that the auth granted signal is actually firing, and it's trying to get the userid or server subscription list. But that somehow the QOAuth2AuthorizationCodeFlow object (m_authenticator) doesn't have a valid token.

**Comment by psiborg112** [comment]
Maybe this is a build issue with Ubuntu, which both @Rjapeck and our build systems are using? If I download the statically linked 1.6.0 binary from here, I have the same login issue. I don't see it when building locally on Debian Sid with either qmake or cmake.

**Comment by nwang92** [comment]
> Maybe this is a build issue with Ubuntu, which both @Rjapeck and our build systems are using? If I download the statically linked 1.6.0 binary from here, I have the same login issue. I don't see it when building locally on Debian Sid with either qmake or cmake.

Could be likely although once we setup the VM using VirtualBox according to the build instructions, the build completed successfully and there were no warnings of any missing packages. The issue seems to manifest in two different ways:
* On initial sign in, the browser opens and "completes" the oauth workflow (according to the success message in the browser) but the app never gets the go ahead to proceed
* On subsequent opens, the app no longer prompts a sign-in message and instead remains in the "Logging in" phase

Both feels like the same root although I don't know exactly what part of the auth chain is broken.

**Comment by psiborg112** [comment]
They are the same root. It seems that for some reason something is going wrong with the auth token that's received. (The app no longer prompts on subsequent opens because there's a saved refresh token.) The build may be completing successfully, but there could be some issue with the version of QNetworkAuth in the library that's being linked under Ubuntu.

**Comment by psiborg112** [comment]
Is anyone able to do a compile on another distro to test? As mentioned, everything is working exactly as expected on Debian Sid.

**Comment by Rjapeck** [comment]
> Is anyone able to do a compile on another distro to test? As mentioned, everything is working exactly as expected on Debian Sid.

I can do it if you'd like.

**Comment by nwang92** [comment]
I got @Rjapeck to add jammy repositories onto his Ubuntu 20.04 VM via:
```bash
russell@russell-VirtualBox:/etc/apt/sources.list.d$ cat jammy.list                                                                                                                                  deb http://mirrors.kernel.org/ubuntu jammy main universe  
```

There were a few package conflict resolution things later, but after updating the entire qt5 stack from 5.12.8 (default with focal) to 5.15.3 (default to jammy), the "Logging in" issue was fixed. So it does seem to be an issue with qt build dependencies, now we'll need to use >=5.15 across all platforms most likely.

**Comment by forsythac** [comment]
Are we able to update the version that github builds with? in other words do we know how to fix?

**Comment by dyfer** [comment]
The reason we build with 5.12.x is in order for the build to run on Ubuntu 20.04. Static builds with 5.15 will not run on 20.04 due to [xcb issue](https://github.com/jacktrip/jacktrip/issues/546),

**Comment by dyfer** [comment]
Another data point:
Ubuntu 20.04, binary from #626 (that uses slightly updated Qt - 5.12.**12**): 
- the issue remains  
- the browser opens and takes me through the login process, but doesn't get past the "Virtual Studio Login Successful" page (doesn't go back to JT)
- the error I get in terminal is `qt.networkauth.oauth2: Unexpected call`

**Comment by psiborg112** [comment]
It's definitely an auth issue in so far as it's most likely a case of the right signal not being emitted by the auth object once authorization is successful. (Either that or there's some sort of connection issue going on with the signal/slot mechanism, although I would think we'd see an issue at compile time if that was the case.) I don't think the 'qt.networkauth.oauth2: Unexpected call' is related: I've seen that happen in normal operation.

**Comment by nwang92** [comment]
Potentially fixed here https://github.com/jacktrip/jacktrip/pull/632

**Comment by dyfer** [comment]
I can now log in on Ubuntu 20.04 using the static Linux build (this is a machine that I was trying to run the previous version on, not a "clean" one).
IMO this could be treated as solved.
