### ISSUE TITLE
cmake build: link fails: ld: error: undefined symbol: vtable for VsPermissions

### ISSUE THREAD

**Issue by yurivict** [jacktrip/jacktrip#828]
```
FAILED: jacktrip 
: && /usr/local/libexec/ccache/c++ -O2 -pipe -fstack-protector-strong -fno-strict-aliasing  -pthread -I/usr/local/include/rtaudio -D__LINUX_PULSE__ -I/usr/local/include -D_REENTRANT -O2 -pipe -fstack-protector-strong -fno-strict-aliasing  -pthread -I/usr/local/include/rtaudio -D__LINUX_PULSE__ -I/usr/local/include -D_REENTRANT   -DNDEBUG -L/usr/local/lib -lrtaudio  -fstack-protector-strong CMakeFiles/jacktrip.dir/jacktrip_autogen/mocs_compilation.cpp.o CMakeFiles/jacktrip.dir/src/main.cpp.o CMakeFiles/jacktrip.dir/src/Settings.cpp.o CMakeFiles/jacktrip.dir/src/jacktrip_globals.cpp.o CMakeFiles/jacktrip.dir/src/JackTrip.cpp.o CMakeFiles/jacktrip.dir/src/UdpHubListener.cpp.o CMakeFiles/jacktrip.dir/src/JackTripWorker.cpp.o CMakeFiles/jacktrip.dir/src/DataProtocol.cpp.o CMakeFiles/jacktrip.dir/src/UdpDataProtocol.cpp.o CMakeFiles/jacktrip.dir/src/AudioInterface.cpp.o CMakeFiles/jacktrip.dir/src/JackAudioInterface.cpp.o CMakeFiles/jacktrip.dir/src/JMess.cpp.o CMakeFiles/jacktrip.dir/src/LoopBack.cpp.o CMakeFiles/jacktrip.dir/src/PacketHeader.cpp.o CMakeFiles/jacktrip.dir/src/RingBuffer.cpp.o CMakeFiles/jacktrip.dir/src/JitterBuffer.cpp.o CMakeFiles/jacktrip.dir/src/Regulator.cpp.o CMakeFiles/jacktrip.dir/src/Compressor.cpp.o CMakeFiles/jacktrip.dir/src/Limiter.cpp.o CMakeFiles/jacktrip.dir/src/Reverb.cpp.o CMakeFiles/jacktrip.dir/src/AudioTester.cpp.o CMakeFiles/jacktrip.dir/src/Patcher.cpp.o CMakeFiles/jacktrip.dir/src/SslServer.cpp.o CMakeFiles/jacktrip.dir/src/Auth.cpp.o CMakeFiles/jacktrip.dir/src/ProcessPlugin.cpp.o CMakeFiles/jacktrip.dir/src/RtAudioInterface.cpp.o CMakeFiles/jacktrip.dir/externals/weakjack/weak_libjack.c.o CMakeFiles/jacktrip.dir/src/gui/qjacktrip.cpp.o CMakeFiles/jacktrip.dir/src/gui/about.cpp.o CMakeFiles/jacktrip.dir/src/gui/messageDialog.cpp.o CMakeFiles/jacktrip.dir/src/gui/textbuf.cpp.o CMakeFiles/jacktrip.dir/src/gui/vuMeter.cpp.o CMakeFiles/jacktrip.dir/src/Meter.cpp.o CMakeFiles/jacktrip.dir/src/gui/virtualstudio.cpp.o CMakeFiles/jacktrip.dir/src/gui/vsQuickView.cpp.o CMakeFiles/jacktrip.dir/src/gui/vsServerInfo.cpp.o CMakeFiles/jacktrip.dir/src/gui/vsPing.cpp.o CMakeFiles/jacktrip.dir/src/gui/vsPinger.cpp.o CMakeFiles/jacktrip.dir/src/gui/vsDevice.cpp.o CMakeFiles/jacktrip.dir/src/gui/vsAudioInterface.cpp.o CMakeFiles/jacktrip.dir/src/gui/vsUrlHandler.cpp.o CMakeFiles/jacktrip.dir/src/gui/vsWebSocket.cpp.o CMakeFiles/jacktrip.dir/src/Volume.cpp.o CMakeFiles/jacktrip.dir/src/Tone.cpp.o CMakeFiles/jacktrip.dir/src/dblsqd/feed.cpp.o CMakeFiles/jacktrip.dir/src/dblsqd/release.cpp.o CMakeFiles/jacktrip.dir/src/dblsqd/semver.cpp.o CMakeFiles/jacktrip.dir/src/dblsqd/update_dialog.cpp.o CMakeFiles/jacktrip.dir/jacktrip_autogen/MXUWEOXILK/qrc_qjacktrip.cpp.o -o jacktrip  -Wl,-rpath,/usr/local/lib/qt5:  /usr/local/lib/qt5/libQt5Widgets.so.5.15.5  /usr/local/lib/qt5/libQt5Quick.so.5.15.5  /usr/local/lib/qt5/libQt5NetworkAuth.so.5.15.5  /usr/local/lib/qt5/libQt5WebSockets.so.5.15.5  /usr/local/lib/qt5/libQt5Gui.so.5.15.5  /usr/local/lib/qt5/libQt5QmlModels.so.5.15.5  /usr/local/lib/qt5/libQt5Qml.so.5.15.5  /usr/local/lib/qt5/libQt5Network.so.5.15.5  /usr/local/lib/qt5/libQt5Core.so.5.15.5 && :
ld: error: undefined symbol: vtable for VsPermissions
>>> referenced by virtualstudio.cpp
>>>               CMakeFiles/jacktrip.dir/src/gui/virtualstudio.cpp.o:(VirtualStudio::VirtualStudio(bool, QObject*))
>>> the vtable symbol may be undefined because the class is missing its key function (see https://lld.llvm.org/missingkeyfunction)

ld: error: undefined symbol: VsPermissions::staticMetaObject
>>> referenced by virtualstudio.cpp
>>>               CMakeFiles/jacktrip.dir/src/gui/virtualstudio.cpp.o:(QMetaTypeIdQObject<VsPermissions*, 8>::qt_metatype_id())
>>> referenced by virtualstudio.cpp
>>>               CMakeFiles/jacktrip.dir/src/gui/virtualstudio.cpp.o:(QMetaTypeIdQObject<VsPermissions*, 8>::qt_metatype_id())
c++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

Version: 1.6.7
Qt-5.15.5
clang-14
FreeBSD 13.1

**Comment by ntonnaett** [comment]
Do you see the same behavior with the meson and qmake builds?

**Comment by yurivict** [comment]
Only cmake has this problem.

**Comment by psiborg112** [comment]
The cmake build setup is used only by me to make non virtual studio builds. It is not maintained for virtual studio builds. There's an explicit warning about this that gets printed when using cmake.

**Comment by psiborg112** [comment]
What will be happening is that undoubtedly some new source file has been added for VS, but this hasn't been added to the CMakeLists.txt file. (Hence undefined symbols when linking.) And this will undoubtedly keep happening because I don't test VS builds, and those working on VS don't use cmake. If you want builds for Virtual Studio enabled versions of JackTrip (which is the default) to keep working as expected, please use meson or qmake as outlined in all of the available documentation.

**Comment by psiborg112** [comment]
This is fixed in #835, but I have to stress that if you continue to insist on using an unofficial built setup that exists purely for development purposes instead of one of the two perfectly working release options that are available to you, then you will keep running into issues. Either switch to one of the two supported options or accept the fact that your chosen build system will remain unsupported. (And know that bugs like this in future will not be a priority to fix.)

**Comment by yurivict** [comment]
There are all kinds of projects. Some migrated from GNU Tools to cmake, but keep GNU Tools makefiles around, some migrate from meson to cmake. It's difficult to guess what is the condition. People generally don't reed every line in CMakeLists.txt

You should make it check the user name and fail for anyone who has a different name. This would attract attention.

**Comment by psiborg112** [comment]
It's all right there in the build documentation though. Step by step instructions for qmake and meson.

**Comment by ntonnaett** [comment]
The output of the cmake build warns about this, because you missed that point in the past. Your FreeBSD port uses meson. There's no reason to change that. If you want to improve the cmake build you are open to open PRs. In the future I will close these issues immediatley.
